[package]
name = "rs-time2double-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [
	"cdylib",
]

[profile.release-wasm]
inherits = "release"
lto = true
strip = true
opt-level = 's'
codegen-units = 16
